name: Build Efiling API Image and Push to Openshift 4 Registry

on:
  schedule:
    - cron: "0 0 * */3 *"
  push:
    branches: [master]
    paths:
      - "src/backend/**"
      - ".github/workflows/dev-efiling-api-build.yaml"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Login to Artifactory
        uses: docker/login-action@v1
        with:
          registry: artifacts.developer.gov.bc.ca
          username: ${{ secrets.EFILING_ARTIFACTORY_USERNAME }}
          password: ${{ secrets.EFILING_ARTIFACTORY_PASSWORD }}
      
      - name: Build Image
        env:
          MVN_PROFILE: efiling-api,splunk
          STARTERS_V: v1.0.3
        run: |
          docker compose build efiling-api

      #Run Vulnerability Scan usinig Trivy scanner
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: jag-file-submission-efiling-api
          image-ref: image:latest
          format: sarif
          output: trivy-results.sarif
          exit-code: 1
          ignore-unfixed: true
          limit-severities-for-sarif: true
          severity: HIGH,CRITICAL

      #Upload results to the Github security tab.
      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: trivy-results.sarif

      
