name: Build Efiling Frontend Image and Push to Openshift Registry

on:
  push:
    branches: [master]
    paths:
      - "src/frontend/efiling-frontend/**"
      - ".github/workflows/dev-efiling-frontend-build.yaml"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Build Image
        run: |
          docker compose build efiling-frontend

      - name: docker image
        id: docker-image
        run: |
          docker images -a

      #Run Vulnerability Scan usinig Trivy scanner
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: image
          image-ref: jag-file-submission-efiling-frontend
          format: sarif
          output: trivy-results.sarif
          exit-code: 1
          ignore-unfixed: true
          limit-severities-for-sarif: true
          severity: HIGH,CRITICAL

      #Upload results to the Github security tab.
      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: trivy-results.sarif


